import { CONFIG, TIME_SLOTS } from "../config.js";
import { db } from "../firebase-init.js";
import { requireAdmin, logout } from "./auth.js";
import { collection, getCountFromServer, getDocs, limit, query } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
const $=id=>document.getElementById(id);const fmtDate=v=>{const d=toDate(v);return d?d.toLocaleString("en-US",{dateStyle:"medium",timeStyle:"short"}):"—"};const toDate=v=>v?.toDate?v.toDate():(typeof v==="string"?new Date(v):null);const title=s=>(s||"").replace(/[-_]+/g," ").replace(/\b\w/g,c=>c.toUpperCase());const slotLabel=id=>TIME_SLOTS.find(s=>s.id===id)?.label||id||"—";const yn=v=>v===true?"Yes":v===false?"No":"—";const emailStatus=r=>r.confirmationEmailSent||r.confirmationSent||r.confirmationEmailStatus==="sent";const consentStatus=r=>r.consentEmailSent||r.consentSent||r.consentEmailStatus==="sent";let regs=[],filtered=[],page=1,sortKey="createdAt",sortDir="desc";const pageSize=25;
function initShell(user){$("admin-email")&&($("admin-email").textContent=user.email);$("drive-meta")&&($("drive-meta").textContent=`${CONFIG.eventName} • ${new Date(CONFIG.bloodDriveDate+"T00:00:00").toLocaleDateString("en-US",{dateStyle:"long"})} • ${CONFIG.location}`);$("logout")?.addEventListener("click",logout)}
requireAdmin({onReady:(user)=>{initShell(user);const path=location.pathname;if(path.endsWith("registrations.html")) initRegistrations(); else if(path.endsWith("statistics.html")) initStats();},onDenied:(m)=>{$("error")&&($("error").textContent=m)}});
async function baseQuery(max=500){return query(collection(db,"registrations"),limit(max))}
function isCurrentDriveRecord(record){return !record.bloodDriveId || record.bloodDriveId===CONFIG.bloodDriveId}
async function loadRegistrations(max=500){const snap=await getDocs(await baseQuery(max));return snap.docs.map(d=>({id:d.id,...d.data()})).filter(isCurrentDriveRecord)}
async function initRegistrations(){fillFilters(); try{const countSnap=await getCountFromServer(collection(db,"registrations"));regs=await loadRegistrations();window.totalOverall=countSnap.data().count;renderHead();bindFilters();applyFilters()}catch(_e){$("counts").textContent="Unable to load registrations";$("rows").innerHTML="<tr><td>Registrations could not be loaded. Confirm admin access is enabled in Firebase and Firestore rules are deployed.</td></tr>";$("error").textContent="Registrations could not be loaded. Confirm admin access is enabled in Firebase and Firestore rules are deployed."}}
function fillFilters(){TIME_SLOTS.forEach(s=>$("filter-slot").append(new Option(s.label,s.id)));["alex-patel","daniel-kim","maya-shah","priya-desai","sarah-chen"].forEach(id=>$("filter-senator").append(new Option(title(id),id)))}
const cols=[['id','Confirmation ID'],['createdAt','Date Submitted'],['firstName','First Name'],['lastName','Last Name'],['parentEmail','Parent Email'],['studentEmail','Personal Student Email'],['phone','Phone'],['dob','Birthdate'],['studentId','Student ID'],['nhsSeniorMember','NHS?'],['senatorIds','Senator(s) Who Assisted'],['appointmentSlotId','Appointment Time'],['ageOnDriveDate','Age on Drive Date'],['confirmation','Confirmation Email Sent'],['consent','Consent Email Sent'],['lastUpdated','Last Updated']];
function renderHead(){const tr=$("head");tr.textContent="";cols.forEach(([k,l])=>{const th=document.createElement("th");th.textContent=l;th.onclick=()=>{sortKey=k;sortDir=sortDir==="asc"?"desc":"asc";applyFilters()};tr.append(th)})}
function bindFilters(){["search","filter-slot","filter-age","filter-nhs","filter-senator","filter-confirmation","filter-consent"].forEach(id=>$(id).addEventListener("input",()=>{page=1;applyFilters()}));$("clear").onclick=()=>{["search","filter-slot","filter-age","filter-nhs","filter-senator","filter-confirmation","filter-consent"].forEach(id=>$(id).value="");page=1;applyFilters()};$("prev").onclick=()=>{page=Math.max(1,page-1);renderRows()};$("next").onclick=()=>{page++;renderRows()}}
function applyFilters(){const q=$("search").value.trim().toLowerCase();filtered=regs.filter(r=>{const searchable=[r.id,r.firstName,r.lastName,r.studentEmail,r.parentEmail,r.studentId].join(" ").toLowerCase();if(q&&!searchable.includes(q))return false;if($("filter-slot").value&&r.appointmentSlotId!==$("filter-slot").value)return false;const age=$("filter-age").value;if(age==="18+"&&Number(r.ageOnDriveDate)<18)return false;if(age&&age!=="18+"&&String(r.ageOnDriveDate)!==age)return false;if($("filter-nhs").value&&String(r.nhsSeniorMember)!==$("filter-nhs").value)return false;if($("filter-senator").value&&!(r.senatorIds||[]).includes($("filter-senator").value))return false;if($("filter-confirmation").value&&($("filter-confirmation").value==="sent")!==emailStatus(r))return false;if($("filter-consent").value){const v=$("filter-consent").value;if(v==="sent"&&!consentStatus(r))return false;if(v==="required"&&r.parentConsentStatus!=="required")return false;if(v==="not_required"&&r.parentConsentStatus!=="not_required")return false}return true});filtered.sort((a,b)=>compare(val(a,sortKey),val(b,sortKey))*(sortDir==="asc"?1:-1));renderRows()}
function val(r,k){if(k==="confirmation")return emailStatus(r);if(k==="consent")return consentStatus(r);if(k==="lastUpdated")return r.lastUpdated||r.updateTime||r.updatedAt;return r[k]}function compare(a,b){const da=toDate(a),db=toDate(b);if(da&&db)return da-db;return String(a??"").localeCompare(String(b??""),undefined,{numeric:true})}
function renderRows(){const start=(page-1)*pageSize,chunk=filtered.slice(start,start+pageSize);$("rows").textContent="";chunk.forEach(r=>{const tr=document.createElement("tr");tr.onclick=()=>showDetail(r);cols.forEach(([k])=>{const td=document.createElement("td");td.textContent=display(r,k);tr.append(td)});$("rows").append(tr)});$("counts").textContent=`${filtered.length} matching • ${window.totalOverall??regs.length} total registrations`;$("page").textContent=`Page ${page} of ${Math.max(1,Math.ceil(filtered.length/pageSize))}`;$("prev").disabled=page<=1;$("next").disabled=start+pageSize>=filtered.length;if(!chunk.length){const tr=document.createElement("tr"),td=document.createElement("td");td.colSpan=cols.length;td.textContent="No registrations match the current filters.";tr.append(td);$("rows").append(tr)}}
function display(r,k){if(k==="id")return r.id;if(k==="createdAt")return fmtDate(r.createdAt);if(k==="lastUpdated")return fmtDate(r.lastUpdated||r.updateTime||r.updatedAt);if(k==="senatorIds")return (r.senatorIds||[]).map(title).join(", ")||"—";if(k==="appointmentSlotId")return slotLabel(r.appointmentSlotId);if(k==="nhsSeniorMember")return yn(r.nhsSeniorMember);if(k==="confirmation")return emailStatus(r)?"Yes":"No";if(k==="consent")return consentStatus(r)?"Yes":(r.parentConsentStatus==="required"?"Required":"Not required");return r[k]??"—"}
function showDetail(r){const root=$("modal-root");root.innerHTML=`<div class="modal"><div class="modal-card"><div class="summary-line"><h2>Registration Detail</h2><button id="close-modal" class="secondary">Close</button></div><div class="detail-grid"></div></div></div>`;const grid=root.querySelector(".detail-grid");cols.concat([['bloodDriveId','Blood Drive ID'],['bloodDriveDate','Blood Drive Date'],['location','Location'],['parentConsentStatus','Parent Consent Status'],['eligibilityAgeConfirmed','Age Confirmed'],['eligibilityNoFallSportConfirmed','No Fall Sport Confirmed']]).forEach(([k,l])=>{const d=document.createElement("div");d.className="detail-item";d.innerHTML=`<div class="detail-label"></div><div class="detail-value"></div>`;d.children[0].textContent=l;d.children[1].textContent=display(r,k);grid.append(d)});$("close-modal").onclick=()=>root.textContent=""}
async function initStats(){try{regs=await loadRegistrations(2000);renderStats(regs)}catch(_e){$("stats").innerHTML="<section class=\"panel\"><p>Statistics could not be loaded. Confirm admin access is enabled in Firebase and Firestore rules are deployed.</p></section>";$("error").textContent="Statistics could not be loaded. Large deployments should move these calculations to server-side aggregate documents."}}
function renderStats(data){const today=new Date(),weekAgo=new Date(today);weekAgo.setDate(today.getDate()-7);const slotCounts=Object.fromEntries(TIME_SLOTS.map(s=>[s.id,0]));const byDate={},byHour={},sen={},ages={16:0,17:0,"18+":0};let consent=0,last24=0,last7=0;data.forEach(r=>{const d=toDate(r.createdAt);if(d){const key=d.toLocaleDateString("en-US",{month:"short",day:"numeric"});byDate[key]=(byDate[key]||0)+1;byHour[d.getHours()]=(byHour[d.getHours()]||0)+1;if(today-d<864e5)last24++;if(d>=weekAgo)last7++} if(slotCounts[r.appointmentSlotId]!=null)slotCounts[r.appointmentSlotId]++;(r.senatorIds||[]).forEach(id=>sen[id]=(sen[id]||0)+1);const a=Number(r.ageOnDriveDate);if(a===16){ages[16]++;consent++}else if(a===17)ages[17]++;else if(a>=18)ages["18+"]++});const total=data.length,capacity=TIME_SLOTS.reduce((s,x)=>s+x.capacity,0),remaining=Math.max(0,capacity-total);const cards=[['Total registrations',total],['Today',countSince(data,0)],['This week',last7],['Remaining appointments',remaining],['16-year-olds',ages[16]],['Students 17+',ages[17]+ages['18+']],['Requiring parent consent',consent],['Last 24 hours',last24]];const stats=$("stats");stats.textContent="";const grid=el('div','grid');cards.forEach(c=>{const card=el('div','stat-card');card.append(el('div','muted',c[0]),el('div','stat-value',String(c[1])));grid.append(card)});stats.append(grid,chartPanel('Registrations over time',byDate),listPanel('Appointment analytics',appointmentRows(slotCounts,total,capacity)),listPanel('Senate leaderboard',leaderRows(sen,total)),listPanel('Age distribution',[`16 — ${ages[16]}`,`17 — ${ages[17]}`,`18+ — ${ages['18+']}`]),listPanel('Additional metrics',[`Average registrations/day — ${avg(byDate)}`,`Highest-registration day — ${highest(byDate)}`,`Registration growth — ${total}`,`Most popular appointment period — ${popularSlot(slotCounts)}`,`Appointments filled — ${Math.round((total/capacity)*100)}%`, `Needs attention — ${data.filter(r=>r.parentConsentStatus==='required'&&!consentStatus(r)).length} consent emails pending`]))}
function countSince(data,days){const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()-days);return data.filter(r=>{const d=toDate(r.createdAt);return d&&d>=start}).length}function avg(o){const v=Object.values(o);return v.length?(v.reduce((a,b)=>a+b,0)/v.length).toFixed(1):'0'}function highest(o){return Object.entries(o).sort((a,b)=>b[1]-a[1])[0]?.join(' — ')||'—'}function popularSlot(o){const e=Object.entries(o).sort((a,b)=>b[1]-a[1])[0];return e?`${slotLabel(e[0])} (${e[1]})`:'—'}function appointmentRows(o){return TIME_SLOTS.map(s=>`${s.label} — ${o[s.id]||0}/${s.capacity}`)}function leaderRows(o,total){return Object.entries(o).sort((a,b)=>b[1]-a[1]).map(([id,n],i)=>`${i+1}. ${title(id)} — ${n} (${total?Math.round(n/total*100):0}%)`)}function chartPanel(t,o){const p=el('section','panel');p.append(el('h2','',t));const c=el('div','chart');const max=Math.max(1,...Object.values(o));Object.entries(o).forEach(([k,v])=>{const b=el('div','bar');b.style.height=`${Math.max(6,v/max*190)}px`;b.title=`${k}: ${v}`;b.append(el('span','',k));c.append(b)});p.append(c,el('p','muted',`Total registrations: ${Object.values(o).reduce((a,b)=>a+b,0)} • Average/day: ${avg(o)} • Highest day: ${highest(o)}`));return p}function listPanel(t,rows){const p=el('section','panel');p.append(el('h2','',t));const l=el('div','list');rows.forEach(r=>l.append(el('div','list-row',r)));p.append(l);return p}function el(tag,cls,text){const e=document.createElement(tag);if(cls)e.className=cls;if(text!=null)e.textContent=text;return e}
